version: '2'

networks:
  orderer_anet:
    external: true

services:

  ca:
    image: hyperledger/fabric-ca:$ARCH-$VERSION
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.$PEER
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.$PEER-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$CA_KEY
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bbc6.sics.se-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$CA_KEY
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/$PEER/ca:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.$PEER
    networks:
      - orderer_anet

  peer0:
    container_name: peer0.$PEER
    image: hyperledger/fabric-peer:$ARCH-$VERSION
    environment:
      - CORE_LOGGING_PEER=ERROR
      - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
      - CORE_CHAINCODE_EXECUTETIMEOUT=90s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.$PEER
      - CORE_PEER_ADDRESS=peer0.$PEER:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=orderer_anet
      - CORE_PEER_LOCALMSPID=KTHMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.$PEER:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=peerpass
      - CORE_PEER_ADDRESSAUTODETECT=false
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - TLSCA_FILE=/etc/hyperledger/fabric/tlsca/tlsca.bbc6.sics.se-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ../data/peer0.$PEER:/var/hyperledger/production
        - /var/run:/host/var/run
        - ../artifacts:/etc/hyperledger/configtx
        - ../crypto-config/peerOrganizations/$PEER/peers/peer0.$PEER/msp:/etc/hyperledger/peer/msp
        - ../crypto-config/peerOrganizations/$PEER/users:/etc/hyperledger/msp/users
        - ../crypto-config/peerOrganizations/$PEER/peers/peer0.$PEER/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/ordererOrganizations/bbc6.sics.se/orderers/orderer.bbc6.sics.se/msp/tlscacerts:/etc/hyperledger/fabric/tlsca
    depends_on:
      - ca
      - couchdb
    networks:
      - orderer_anet

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:$ARCH-$VERSION
    ports:
      - 5984:5984
    environment:
      - DB_URL=http://localhost:5984/member_db
      - COUCHDB_USER=peer0
      - COUCHDB_PASSWORD=peerpass
    volumes:
      - ../data/couchdb0:/opt/couchdb/data
    networks:
      - orderer_anet
